name: Convert .h5 Model to TensorFlow.js and Download

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read  # Read permission for the repository contents (no need to write)

jobs:
  convert-model:
    runs-on: ubuntu-latest  # Use Ubuntu for the job

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Use Python 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow==2.12.0 tensorflowjs numpy  # Install required dependencies

    - name: Convert model from .h5 to tfjs format
      run: |
        tensorflowjs_converter --input_format keras models/model.h5 models/tfjs_model  # Convert .h5 to TensorFlow.js format

    - name: Zip the converted TensorFlow.js model
      run: |
        zip -r models/tfjs_model.zip models/tfjs_model  # Zip the model directory into a .zip file

    - name: Upload the zip file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: tfjs-model  # Name of the artifact
        path: models/tfjs_model.zip  # Path to the zip file
